apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubepack:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - kubepack.com
  resources:
  - packs
  - packs/releases
  - users
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubepack:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - kubepack.com
  resources:
  - packs
  - packs/releases
  - users
  verbs:
  - get
  - list
  - watch
