# sample:
# - https://github.com/kubernetes/apiserver/blob/230bc6c645825161e07cc4dc79b8055b84d4f516/pkg/apis/audit/types.go#L145
# - https://raw.githubusercontent.com/kubernetes/website/master/docs/tasks/debug-application-cluster/audit-policy.yaml
# - https://github.com/kubernetes/kubernetes/blob/411881803f20a6c7390588dc194945c2d575e5df/cluster/gce/gci/configure-helper.sh#L703
apiVersion: audit.k8s.io/v1beta1
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
  - "RequestReceived"
rules:
- level: RequestResponse
  # users: ["system:serviceaccount:<namespace>:<serviceaccount-name>"]
  resources:
  - group: "" # core
    resources: ["pods", "secrets"]
  - group: "extensions"
    resources: ["deployments"]
