apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://<PRIMARY_NETWORK_INTERFACE_IP>:8080/events
  name: hit-config
contexts:
- context:
    cluster: hit-config
    user: ""
  name: webhook
current-context: webhook
users: []
preferences: {}